name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          sudo wget -O cloudflared "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
          sudo mv cloudflared /usr/local/bin
          sudo chmod +x /usr/local/bin/cloudflared

          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key

          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no 
            ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h
          END
          
          ssh deploy 'rm -rfv /home/pi/pipeline_test && mkdir /home/pi/pipeline_test'
          
          scp -r ./public/. deploy:/home/pi/pipeline_test/
          
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
