name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          sudo wget -O cloudflared "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
          sudo mv cloudflared /usr/local/bin
          sudo chmod +x /usr/local/bin/cloudflared
          
          cloudflared -v
          
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/pi.key
          chmod 600 ~/.ssh/pi.key
          
          sudo ssh pi@ssh.joewill.co.uk -o ProxyCommand='sudo cloudflared access ssh --service-token-id "$CLOUDFLARED_ACCESS_ID" --service-token-secret "$CLOUDFLARED_ACCESS_CLIENT_SECRET" --hostname %h' -i ~/.ssh/pi.key 
          ls
          exit
          
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          CLOUDFLARED_ACCESS_CLIENT_SECRET: ${{ secrets.CLOUDFLARED_ACCESS_CLIENT_SECRET }}
          CLOUDFLARED_ACCESS_ID: ${{ secrets.CLOUDFLARED_ACCESS_ID }}
