name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          wget "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/pi.key
          chmod 600 ~/.ssh/pi.key
          
          ssh pi@ssh.joewill.co.uk -o ProxyCommand='~/cloudflared-linux-amd64 access ssh --service-token-id 0ea2af1051e4535b8f0a61257ec23135.access --service-token-secret c82dbc74b4c5d67d4e3bfda32030 --hostname %h' -i ~/.ssh/pi_key 
          ls
          exit
          
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
